/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.ssoready.api.resources.management;

import com.ssoready.api.core.ClientOptions;
import com.ssoready.api.core.Suppliers;
import com.ssoready.api.resources.management.organizations.OrganizationsClient;
import com.ssoready.api.resources.management.samlconnections.SamlConnectionsClient;
import com.ssoready.api.resources.management.scimdirectories.ScimDirectoriesClient;
import com.ssoready.api.resources.management.setupurls.SetupUrlsClient;
import java.util.function.Supplier;

public class ManagementClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<OrganizationsClient> organizationsClient;

    protected final Supplier<SamlConnectionsClient> samlConnectionsClient;

    protected final Supplier<ScimDirectoriesClient> scimDirectoriesClient;

    protected final Supplier<SetupUrlsClient> setupUrlsClient;

    public ManagementClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.organizationsClient = Suppliers.memoize(() -> new OrganizationsClient(clientOptions));
        this.samlConnectionsClient = Suppliers.memoize(() -> new SamlConnectionsClient(clientOptions));
        this.scimDirectoriesClient = Suppliers.memoize(() -> new ScimDirectoriesClient(clientOptions));
        this.setupUrlsClient = Suppliers.memoize(() -> new SetupUrlsClient(clientOptions));
    }

    public OrganizationsClient organizations() {
        return this.organizationsClient.get();
    }

    public SamlConnectionsClient samlConnections() {
        return this.samlConnectionsClient.get();
    }

    public ScimDirectoriesClient scimDirectories() {
        return this.scimDirectoriesClient.get();
    }

    public SetupUrlsClient setupUrls() {
        return this.setupUrlsClient.get();
    }
}
