/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.ssoready.api.core;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class SSOReadyException extends RuntimeException {
    public SSOReadyException(String message) {
        super(message);
    }

    public SSOReadyException(String message, Exception e) {
        super(message, e);
    }
}
