/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.ssoready.api.resources.saml;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.ssoready.api.core.ClientOptions;
import com.ssoready.api.core.MediaTypes;
import com.ssoready.api.core.ObjectMappers;
import com.ssoready.api.core.RequestOptions;
import com.ssoready.api.core.SSOReadyException;
import com.ssoready.api.core.SsoreadyApiApiException;
import com.ssoready.api.resources.saml.requests.GetSamlRedirectUrlRequest;
import com.ssoready.api.resources.saml.requests.RedeemSamlAccessCodeRequest;
import com.ssoready.api.types.GetSamlRedirectUrlResponse;
import com.ssoready.api.types.RedeemSamlAccessCodeResponse;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class SamlClient {
    protected final ClientOptions clientOptions;

    public SamlClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Exchanges a SAML access code for details about your user's SAML login details.
     */
    public RedeemSamlAccessCodeResponse redeemSamlAccessCode() {
        return redeemSamlAccessCode(RedeemSamlAccessCodeRequest.builder().build());
    }

    /**
     * Exchanges a SAML access code for details about your user's SAML login details.
     */
    public RedeemSamlAccessCodeResponse redeemSamlAccessCode(RedeemSamlAccessCodeRequest request) {
        return redeemSamlAccessCode(request, null);
    }

    /**
     * Exchanges a SAML access code for details about your user's SAML login details.
     */
    public RedeemSamlAccessCodeResponse redeemSamlAccessCode(
            RedeemSamlAccessCodeRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/saml/redeem")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new SSOReadyException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), RedeemSamlAccessCodeResponse.class);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new SsoreadyApiApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
        } catch (IOException e) {
            throw new SSOReadyException("Network error executing HTTP request", e);
        }
    }

    /**
     * Gets a SAML initiation URL to redirect your users to.
     */
    public GetSamlRedirectUrlResponse getSamlRedirectUrl() {
        return getSamlRedirectUrl(GetSamlRedirectUrlRequest.builder().build());
    }

    /**
     * Gets a SAML initiation URL to redirect your users to.
     */
    public GetSamlRedirectUrlResponse getSamlRedirectUrl(GetSamlRedirectUrlRequest request) {
        return getSamlRedirectUrl(request, null);
    }

    /**
     * Gets a SAML initiation URL to redirect your users to.
     */
    public GetSamlRedirectUrlResponse getSamlRedirectUrl(
            GetSamlRedirectUrlRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/saml/redirect")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new SSOReadyException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), GetSamlRedirectUrlResponse.class);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new SsoreadyApiApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
        } catch (IOException e) {
            throw new SSOReadyException("Network error executing HTTP request", e);
        }
    }
}
