/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.ssoready.api.resources.management.organizations.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.ssoready.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OrganizationsListOrganizationsRequest.Builder.class)
public final class OrganizationsListOrganizationsRequest {
    private final Optional<String> pageToken;

    private final Map<String, Object> additionalProperties;

    private OrganizationsListOrganizationsRequest(
            Optional<String> pageToken, Map<String, Object> additionalProperties) {
        this.pageToken = pageToken;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Pagination token. Leave empty to get the first page of results.
     */
    @JsonProperty("pageToken")
    public Optional<String> getPageToken() {
        return pageToken;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof OrganizationsListOrganizationsRequest
                && equalTo((OrganizationsListOrganizationsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(OrganizationsListOrganizationsRequest other) {
        return pageToken.equals(other.pageToken);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.pageToken);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> pageToken = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(OrganizationsListOrganizationsRequest other) {
            pageToken(other.getPageToken());
            return this;
        }

        @JsonSetter(value = "pageToken", nulls = Nulls.SKIP)
        public Builder pageToken(Optional<String> pageToken) {
            this.pageToken = pageToken;
            return this;
        }

        public Builder pageToken(String pageToken) {
            this.pageToken = Optional.ofNullable(pageToken);
            return this;
        }

        public OrganizationsListOrganizationsRequest build() {
            return new OrganizationsListOrganizationsRequest(pageToken, additionalProperties);
        }
    }
}
