/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.ssoready.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.ssoready.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateScimDirectoryResponse.Builder.class)
public final class CreateScimDirectoryResponse {
    private final Optional<ScimDirectory> scimDirectory;

    private final Map<String, Object> additionalProperties;

    private CreateScimDirectoryResponse(
            Optional<ScimDirectory> scimDirectory, Map<String, Object> additionalProperties) {
        this.scimDirectory = scimDirectory;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The updated SCIM directory.
     */
    @JsonProperty("scimDirectory")
    public Optional<ScimDirectory> getScimDirectory() {
        return scimDirectory;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateScimDirectoryResponse && equalTo((CreateScimDirectoryResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateScimDirectoryResponse other) {
        return scimDirectory.equals(other.scimDirectory);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.scimDirectory);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<ScimDirectory> scimDirectory = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CreateScimDirectoryResponse other) {
            scimDirectory(other.getScimDirectory());
            return this;
        }

        @JsonSetter(value = "scimDirectory", nulls = Nulls.SKIP)
        public Builder scimDirectory(Optional<ScimDirectory> scimDirectory) {
            this.scimDirectory = scimDirectory;
            return this;
        }

        public Builder scimDirectory(ScimDirectory scimDirectory) {
            this.scimDirectory = Optional.ofNullable(scimDirectory);
            return this;
        }

        public CreateScimDirectoryResponse build() {
            return new CreateScimDirectoryResponse(scimDirectory, additionalProperties);
        }
    }
}
