/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.ssoready.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.ssoready.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetOrganizationResponse.Builder.class)
public final class GetOrganizationResponse {
    private final Optional<Organization> organization;

    private final Map<String, Object> additionalProperties;

    private GetOrganizationResponse(Optional<Organization> organization, Map<String, Object> additionalProperties) {
        this.organization = organization;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The requested organization.
     */
    @JsonProperty("organization")
    public Optional<Organization> getOrganization() {
        return organization;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetOrganizationResponse && equalTo((GetOrganizationResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetOrganizationResponse other) {
        return organization.equals(other.organization);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.organization);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Organization> organization = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetOrganizationResponse other) {
            organization(other.getOrganization());
            return this;
        }

        @JsonSetter(value = "organization", nulls = Nulls.SKIP)
        public Builder organization(Optional<Organization> organization) {
            this.organization = organization;
            return this;
        }

        public Builder organization(Organization organization) {
            this.organization = Optional.ofNullable(organization);
            return this;
        }

        public GetOrganizationResponse build() {
            return new GetOrganizationResponse(organization, additionalProperties);
        }
    }
}
