/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.ssoready.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.ssoready.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetScimUserResponse.Builder.class)
public final class GetScimUserResponse {
    private final Optional<ScimUser> scimUser;

    private final Map<String, Object> additionalProperties;

    private GetScimUserResponse(Optional<ScimUser> scimUser, Map<String, Object> additionalProperties) {
        this.scimUser = scimUser;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The requested SCIM user.
     */
    @JsonProperty("scimUser")
    public Optional<ScimUser> getScimUser() {
        return scimUser;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetScimUserResponse && equalTo((GetScimUserResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetScimUserResponse other) {
        return scimUser.equals(other.scimUser);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.scimUser);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<ScimUser> scimUser = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetScimUserResponse other) {
            scimUser(other.getScimUser());
            return this;
        }

        @JsonSetter(value = "scimUser", nulls = Nulls.SKIP)
        public Builder scimUser(Optional<ScimUser> scimUser) {
            this.scimUser = scimUser;
            return this;
        }

        public Builder scimUser(ScimUser scimUser) {
            this.scimUser = Optional.ofNullable(scimUser);
            return this;
        }

        public GetScimUserResponse build() {
            return new GetScimUserResponse(scimUser, additionalProperties);
        }
    }
}
