/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.ssoready.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.ssoready.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetScimGroupResponse.Builder.class)
public final class GetScimGroupResponse {
    private final Optional<ScimGroup> scimGroup;

    private final Map<String, Object> additionalProperties;

    private GetScimGroupResponse(Optional<ScimGroup> scimGroup, Map<String, Object> additionalProperties) {
        this.scimGroup = scimGroup;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The requested SCIM group.
     */
    @JsonProperty("scimGroup")
    public Optional<ScimGroup> getScimGroup() {
        return scimGroup;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetScimGroupResponse && equalTo((GetScimGroupResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetScimGroupResponse other) {
        return scimGroup.equals(other.scimGroup);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.scimGroup);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<ScimGroup> scimGroup = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetScimGroupResponse other) {
            scimGroup(other.getScimGroup());
            return this;
        }

        @JsonSetter(value = "scimGroup", nulls = Nulls.SKIP)
        public Builder scimGroup(Optional<ScimGroup> scimGroup) {
            this.scimGroup = scimGroup;
            return this;
        }

        public Builder scimGroup(ScimGroup scimGroup) {
            this.scimGroup = Optional.ofNullable(scimGroup);
            return this;
        }

        public GetScimGroupResponse build() {
            return new GetScimGroupResponse(scimGroup, additionalProperties);
        }
    }
}
