/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.ssoready.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.ssoready.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetSamlRedirectUrlResponse.Builder.class)
public final class GetSamlRedirectUrlResponse {
    private final Optional<String> redirectUrl;

    private final Map<String, Object> additionalProperties;

    private GetSamlRedirectUrlResponse(Optional<String> redirectUrl, Map<String, Object> additionalProperties) {
        this.redirectUrl = redirectUrl;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Redirect your user to this URL to start a SAML login.
     */
    @JsonProperty("redirectUrl")
    public Optional<String> getRedirectUrl() {
        return redirectUrl;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetSamlRedirectUrlResponse && equalTo((GetSamlRedirectUrlResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetSamlRedirectUrlResponse other) {
        return redirectUrl.equals(other.redirectUrl);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.redirectUrl);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> redirectUrl = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetSamlRedirectUrlResponse other) {
            redirectUrl(other.getRedirectUrl());
            return this;
        }

        @JsonSetter(value = "redirectUrl", nulls = Nulls.SKIP)
        public Builder redirectUrl(Optional<String> redirectUrl) {
            this.redirectUrl = redirectUrl;
            return this;
        }

        public Builder redirectUrl(String redirectUrl) {
            this.redirectUrl = Optional.ofNullable(redirectUrl);
            return this;
        }

        public GetSamlRedirectUrlResponse build() {
            return new GetSamlRedirectUrlResponse(redirectUrl, additionalProperties);
        }
    }
}
