/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.ssoready.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.ssoready.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListOrganizationsResponse.Builder.class)
public final class ListOrganizationsResponse {
    private final Optional<List<Organization>> organizations;

    private final Optional<String> nextPageToken;

    private final Map<String, Object> additionalProperties;

    private ListOrganizationsResponse(
            Optional<List<Organization>> organizations,
            Optional<String> nextPageToken,
            Map<String, Object> additionalProperties) {
        this.organizations = organizations;
        this.nextPageToken = nextPageToken;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return List of organizations.
     */
    @JsonProperty("organizations")
    public Optional<List<Organization>> getOrganizations() {
        return organizations;
    }

    /**
     * @return Value to use as <code>pageToken</code> for the next page of data. Empty if there is no more data.
     */
    @JsonProperty("nextPageToken")
    public Optional<String> getNextPageToken() {
        return nextPageToken;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListOrganizationsResponse && equalTo((ListOrganizationsResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListOrganizationsResponse other) {
        return organizations.equals(other.organizations) && nextPageToken.equals(other.nextPageToken);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.organizations, this.nextPageToken);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<Organization>> organizations = Optional.empty();

        private Optional<String> nextPageToken = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListOrganizationsResponse other) {
            organizations(other.getOrganizations());
            nextPageToken(other.getNextPageToken());
            return this;
        }

        @JsonSetter(value = "organizations", nulls = Nulls.SKIP)
        public Builder organizations(Optional<List<Organization>> organizations) {
            this.organizations = organizations;
            return this;
        }

        public Builder organizations(List<Organization> organizations) {
            this.organizations = Optional.ofNullable(organizations);
            return this;
        }

        @JsonSetter(value = "nextPageToken", nulls = Nulls.SKIP)
        public Builder nextPageToken(Optional<String> nextPageToken) {
            this.nextPageToken = nextPageToken;
            return this;
        }

        public Builder nextPageToken(String nextPageToken) {
            this.nextPageToken = Optional.ofNullable(nextPageToken);
            return this;
        }

        public ListOrganizationsResponse build() {
            return new ListOrganizationsResponse(organizations, nextPageToken, additionalProperties);
        }
    }
}
