/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.ssoready.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.ssoready.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListScimDirectoriesResponse.Builder.class)
public final class ListScimDirectoriesResponse {
    private final Optional<List<ScimDirectory>> scimDirectories;

    private final Optional<String> nextPageToken;

    private final Map<String, Object> additionalProperties;

    private ListScimDirectoriesResponse(
            Optional<List<ScimDirectory>> scimDirectories,
            Optional<String> nextPageToken,
            Map<String, Object> additionalProperties) {
        this.scimDirectories = scimDirectories;
        this.nextPageToken = nextPageToken;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The list of SCIM directories.
     */
    @JsonProperty("scimDirectories")
    public Optional<List<ScimDirectory>> getScimDirectories() {
        return scimDirectories;
    }

    /**
     * @return Value to use as <code>pageToken</code> for the next page of data. Empty if there is no more data.
     */
    @JsonProperty("nextPageToken")
    public Optional<String> getNextPageToken() {
        return nextPageToken;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListScimDirectoriesResponse && equalTo((ListScimDirectoriesResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListScimDirectoriesResponse other) {
        return scimDirectories.equals(other.scimDirectories) && nextPageToken.equals(other.nextPageToken);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.scimDirectories, this.nextPageToken);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<ScimDirectory>> scimDirectories = Optional.empty();

        private Optional<String> nextPageToken = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListScimDirectoriesResponse other) {
            scimDirectories(other.getScimDirectories());
            nextPageToken(other.getNextPageToken());
            return this;
        }

        @JsonSetter(value = "scimDirectories", nulls = Nulls.SKIP)
        public Builder scimDirectories(Optional<List<ScimDirectory>> scimDirectories) {
            this.scimDirectories = scimDirectories;
            return this;
        }

        public Builder scimDirectories(List<ScimDirectory> scimDirectories) {
            this.scimDirectories = Optional.ofNullable(scimDirectories);
            return this;
        }

        @JsonSetter(value = "nextPageToken", nulls = Nulls.SKIP)
        public Builder nextPageToken(Optional<String> nextPageToken) {
            this.nextPageToken = nextPageToken;
            return this;
        }

        public Builder nextPageToken(String nextPageToken) {
            this.nextPageToken = Optional.ofNullable(nextPageToken);
            return this;
        }

        public ListScimDirectoriesResponse build() {
            return new ListScimDirectoriesResponse(scimDirectories, nextPageToken, additionalProperties);
        }
    }
}
