/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.ssoready.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.ssoready.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = RotateScimDirectoryBearerTokenResponse.Builder.class)
public final class RotateScimDirectoryBearerTokenResponse {
    private final Optional<String> bearerToken;

    private final Map<String, Object> additionalProperties;

    private RotateScimDirectoryBearerTokenResponse(
            Optional<String> bearerToken, Map<String, Object> additionalProperties) {
        this.bearerToken = bearerToken;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The new, updated bearer token.
     * <p>Do not log or store this bearer token. It is an authentication token that your customer should securely input into
     * their Identity Provider.</p>
     */
    @JsonProperty("bearerToken")
    public Optional<String> getBearerToken() {
        return bearerToken;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof RotateScimDirectoryBearerTokenResponse
                && equalTo((RotateScimDirectoryBearerTokenResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(RotateScimDirectoryBearerTokenResponse other) {
        return bearerToken.equals(other.bearerToken);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.bearerToken);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> bearerToken = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(RotateScimDirectoryBearerTokenResponse other) {
            bearerToken(other.getBearerToken());
            return this;
        }

        @JsonSetter(value = "bearerToken", nulls = Nulls.SKIP)
        public Builder bearerToken(Optional<String> bearerToken) {
            this.bearerToken = bearerToken;
            return this;
        }

        public Builder bearerToken(String bearerToken) {
            this.bearerToken = Optional.ofNullable(bearerToken);
            return this;
        }

        public RotateScimDirectoryBearerTokenResponse build() {
            return new RotateScimDirectoryBearerTokenResponse(bearerToken, additionalProperties);
        }
    }
}
