/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.ssoready.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.ssoready.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateSamlConnectionResponse.Builder.class)
public final class UpdateSamlConnectionResponse {
    private final Optional<SamlConnection> samlConnection;

    private final Map<String, Object> additionalProperties;

    private UpdateSamlConnectionResponse(
            Optional<SamlConnection> samlConnection, Map<String, Object> additionalProperties) {
        this.samlConnection = samlConnection;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The updated SAML connection.
     */
    @JsonProperty("samlConnection")
    public Optional<SamlConnection> getSamlConnection() {
        return samlConnection;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateSamlConnectionResponse && equalTo((UpdateSamlConnectionResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateSamlConnectionResponse other) {
        return samlConnection.equals(other.samlConnection);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.samlConnection);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<SamlConnection> samlConnection = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdateSamlConnectionResponse other) {
            samlConnection(other.getSamlConnection());
            return this;
        }

        @JsonSetter(value = "samlConnection", nulls = Nulls.SKIP)
        public Builder samlConnection(Optional<SamlConnection> samlConnection) {
            this.samlConnection = samlConnection;
            return this;
        }

        public Builder samlConnection(SamlConnection samlConnection) {
            this.samlConnection = Optional.ofNullable(samlConnection);
            return this;
        }

        public UpdateSamlConnectionResponse build() {
            return new UpdateSamlConnectionResponse(samlConnection, additionalProperties);
        }
    }
}
