/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.ssoready.api.resources.management.setupurls;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.ssoready.api.core.ClientOptions;
import com.ssoready.api.core.MediaTypes;
import com.ssoready.api.core.ObjectMappers;
import com.ssoready.api.core.RequestOptions;
import com.ssoready.api.core.SSOReadyException;
import com.ssoready.api.core.SsoreadyApiApiException;
import com.ssoready.api.resources.management.setupurls.requests.CreateSetupUrlRequest;
import com.ssoready.api.types.CreateSetupUrlResponse;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class SetupUrlsClient {
    protected final ClientOptions clientOptions;

    public SetupUrlsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Creates a short-lived self-serve setup URL that you can send to your customer.
     * <p>Setup URLs let your customer configure their SAML settings, SCIM settings, or both.</p>
     */
    public CreateSetupUrlResponse createSetupUrl() {
        return createSetupUrl(CreateSetupUrlRequest.builder().build());
    }

    /**
     * Creates a short-lived self-serve setup URL that you can send to your customer.
     * <p>Setup URLs let your customer configure their SAML settings, SCIM settings, or both.</p>
     */
    public CreateSetupUrlResponse createSetupUrl(CreateSetupUrlRequest request) {
        return createSetupUrl(request, null);
    }

    /**
     * Creates a short-lived self-serve setup URL that you can send to your customer.
     * <p>Setup URLs let your customer configure their SAML settings, SCIM settings, or both.</p>
     */
    public CreateSetupUrlResponse createSetupUrl(CreateSetupUrlRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/setup-urls")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new SSOReadyException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), CreateSetupUrlResponse.class);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new SsoreadyApiApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
        } catch (IOException e) {
            throw new SSOReadyException("Network error executing HTTP request", e);
        }
    }
}
