/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.ssoready.api;

import com.ssoready.api.core.ClientOptions;
import com.ssoready.api.core.Environment;

public final class SsoreadyApiClientBuilder {
    private ClientOptions.Builder clientOptionsBuilder = ClientOptions.builder();

    private String apiKey = System.getenv("SSOREADY_API_KEY");

    private Environment environment = Environment.DEFAULT;

    /**
     * Sets apiKey.
     * Defaults to the SSOREADY_API_KEY environment variable.
     */
    public SsoreadyApiClientBuilder apiKey(String apiKey) {
        this.apiKey = apiKey;
        return this;
    }

    public SsoreadyApiClientBuilder environment(Environment environment) {
        this.environment = environment;
        return this;
    }

    public SsoreadyApiClientBuilder url(String url) {
        this.environment = Environment.custom(url);
        return this;
    }

    public SsoreadyApiClient build() {
        if (apiKey == null) {
            throw new RuntimeException("Please provide apiKey or set the SSOREADY_API_KEY environment variable.");
        }
        this.clientOptionsBuilder.addHeader("Authorization", "Bearer " + this.apiKey);
        clientOptionsBuilder.environment(this.environment);
        return new SsoreadyApiClient(clientOptionsBuilder.build());
    }
}
