/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.ssoready.api;

import com.ssoready.api.core.ClientOptions;
import com.ssoready.api.core.Suppliers;
import com.ssoready.api.resources.management.ManagementClient;
import com.ssoready.api.resources.saml.SamlClient;
import com.ssoready.api.resources.scim.ScimClient;
import java.util.function.Supplier;

public class SSOReady {
    protected final ClientOptions clientOptions;

    protected final Supplier<SamlClient> samlClient;

    protected final Supplier<ScimClient> scimClient;

    protected final Supplier<ManagementClient> managementClient;

    public SSOReady(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.samlClient = Suppliers.memoize(() -> new SamlClient(clientOptions));
        this.scimClient = Suppliers.memoize(() -> new ScimClient(clientOptions));
        this.managementClient = Suppliers.memoize(() -> new ManagementClient(clientOptions));
    }

    public SamlClient saml() {
        return this.samlClient.get();
    }

    public ScimClient scim() {
        return this.scimClient.get();
    }

    public ManagementClient management() {
        return this.managementClient.get();
    }

    public static SSOReadyBuilder builder() {
        return new SSOReadyBuilder();
    }
}
